"""
Clinical report generator for UterusScope-AI.
"""

from __future__ import annotations

import base64
import io
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional, Union

import cv2
import numpy as np
from jinja2 import Environment, BaseLoader

from uterus_scope.config import get_config, ReportFormat
from uterus_scope.models.unified import ModelOutput
from uterus_scope.agents.decision import DecisionResult

logger = logging.getLogger(__name__)


REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UterusScope-AI Clinical Report</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { background: #2c3e50; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 24px; }
        .disclaimer { background: #fee2e2; border-left: 4px solid #ef4444; padding: 12px; margin: 20px 0; }
        .section { background: #f8f9fa; padding: 16px; border-radius: 8px; margin: 16px 0; }
        .section h2 { color: #2c3e50; margin-top: 0; font-size: 18px; border-bottom: 2px solid #3498db; padding-bottom: 8px; }
        .metric { display: inline-block; padding: 12px 20px; margin: 8px; background: white; border-radius: 6px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .metric-label { font-size: 12px; color: #666; }
        .metric-value { font-size: 24px; font-weight: bold; color: #2c3e50; }
        .alert-normal { color: #059669; }
        .alert-attention { color: #d97706; }
        .alert-warning { color: #dc2626; }
        .alert-critical { color: #7c2d12; background: #fee2e2; }
        .candidacy { padding: 16px; border-radius: 8px; margin: 16px 0; }
        .excellent { background: #d1fae5; border-left: 4px solid #059669; }
        .good { background: #dbeafe; border-left: 4px solid #3b82f6; }
        .cautionary { background: #fef3c7; border-left: 4px solid #d97706; }
        .not-recommended { background: #fee2e2; border-left: 4px solid #dc2626; }
        .heatmap-container { display: flex; gap: 16px; flex-wrap: wrap; margin: 16px 0; }
        .heatmap-item { text-align: center; }
        .heatmap-item img { max-width: 200px; border-radius: 8px; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f3f4f6; font-weight: 600; }
        .footer { text-align: center; color: #666; font-size: 12px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🔬 UterusScope-AI Clinical Report</h1>
        <p>Analysis ID: {{ analysis_id }} | Generated: {{ timestamp }}</p>
    </div>
    
    <div class="disclaimer">
        <strong>⚠️ Medical Disclaimer:</strong> This report is generated by an AI system and is intended as a clinical decision support tool only. 
        All findings require review and validation by qualified healthcare professionals before any clinical decisions are made.
    </div>
    
    <div class="section">
        <h2>📊 Measurements Summary</h2>
        <div class="metric">
            <div class="metric-label">Endometrial Thickness</div>
            <div class="metric-value">{{ thickness_mm }} mm</div>
        </div>
        <div class="metric">
            <div class="metric-label">Vascularity</div>
            <div class="metric-value">{{ vascularity_type }}</div>
        </div>
        <div class="metric">
            <div class="metric-label">Fibrosis Score</div>
            <div class="metric-value">{{ fibrosis_score }}</div>
        </div>
        <div class="metric">
            <div class="metric-label">Confidence</div>
            <div class="metric-value">{{ confidence }}%</div>
        </div>
    </div>
    
    <div class="section candidacy {{ candidacy_class }}">
        <h2>🎯 UG-IHI Candidacy Assessment</h2>
        <p><strong>Status:</strong> {{ candidacy_status }}</p>
        <p>{{ candidacy_summary }}</p>
        {% if contraindications %}
        <p><strong>Considerations:</strong></p>
        <ul>
            {% for item in contraindications %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    
    <div class="section">
        <h2>📋 Detailed Findings</h2>
        <table>
            <tr><th>Finding</th><th>Value</th><th>Status</th><th>Notes</th></tr>
            {% for finding in findings %}
            <tr>
                <td>{{ finding.name }}</td>
                <td>{{ finding.value }}{% if finding.unit %} {{ finding.unit }}{% endif %}</td>
                <td class="alert-{{ finding.alert_level }}">{{ finding.alert_level | upper }}</td>
                <td>{{ finding.description }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    
    {% if heatmaps %}
    <div class="section">
        <h2>🔥 Explainability Heatmaps</h2>
        <div class="heatmap-container">
            {% for name, data in heatmaps.items() %}
            <div class="heatmap-item">
                <img src="data:image/png;base64,{{ data }}" alt="{{ name }}">
                <p>{{ name }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    
    <div class="section">
        <h2>💡 Recommendations</h2>
        <ul>
            {% for rec in recommendations %}
            <li>{{ rec }}</li>
            {% endfor %}
        </ul>
    </div>
    
    <div class="footer">
        <p>Generated by UterusScope-AI v{{ version }}</p>
        <p>This report is for clinical decision support purposes only.</p>
    </div>
</body>
</html>
"""


class ClinicalReportGenerator:
    """Generate clinical reports from analysis results."""
    
    def __init__(self, output_dir: Optional[Path] = None):
        config = get_config()
        self.output_dir = output_dir or config.report.output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.env = Environment(loader=BaseLoader())
        self.template = self.env.from_string(REPORT_TEMPLATE)
    
    def generate(
        self,
        model_output: ModelOutput,
        decision_result: DecisionResult,
        analysis_id: str,
        heatmaps: Optional[dict[str, np.ndarray]] = None,
        format: ReportFormat = ReportFormat.HTML,
    ) -> Path:
        """Generate clinical report."""
        # Prepare data
        thickness = self._get_value(model_output.segmentation.thickness_mm)
        vasc_type = self._get_value(model_output.vascularity.predicted_type)
        fibrosis = self._get_value(model_output.fibrosis.severity_score)
        confidence = self._get_value(model_output.overall_confidence)
        
        vasc_names = {0: "Type 0 (Avascular)", 1: "Type I (Minimal)", 2: "Type II (Moderate)", 3: "Type III (High)"}
        
        # Encode heatmaps
        encoded_heatmaps = {}
        if heatmaps:
            for name, hm in heatmaps.items():
                encoded_heatmaps[name] = self._encode_image(hm)
        
        # Render template
        html = self.template.render(
            analysis_id=analysis_id,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            thickness_mm=f"{thickness:.1f}",
            vascularity_type=vasc_names.get(int(vasc_type), f"Type {vasc_type}"),
            fibrosis_score=f"{fibrosis:.2f}",
            confidence=f"{confidence * 100:.0f}",
            candidacy_status=decision_result.candidacy.value.replace('_', ' ').title(),
            candidacy_summary=decision_result.summary,
            candidacy_class=decision_result.candidacy.value.replace('_', '-'),
            contraindications=decision_result.contraindications,
            findings=[f.__dict__ for f in decision_result.findings],
            recommendations=decision_result.reasoning + [r for f in decision_result.findings if f.recommendation for r in [f.recommendation]],
            heatmaps=encoded_heatmaps,
            version="0.1.0",
        )
        
        # Save report
        output_path = self.output_dir / f"{analysis_id}_report.html"
        output_path.write_text(html)
        
        # Convert to PDF if requested
        if format == ReportFormat.PDF:
            pdf_path = self._convert_to_pdf(output_path)
            return pdf_path
        
        return output_path
    
    def _get_value(self, tensor_or_value) -> float:
        if hasattr(tensor_or_value, 'item'):
            return tensor_or_value.item()
        if hasattr(tensor_or_value, '__getitem__'):
            return float(tensor_or_value[0])
        return float(tensor_or_value) if tensor_or_value is not None else 0.0
    
    def _encode_image(self, image: np.ndarray) -> str:
        if image.max() <= 1.0:
            image = (image * 255).astype(np.uint8)
        if len(image.shape) == 2:
            image = cv2.cvtColor(image.astype(np.uint8), cv2.COLOR_GRAY2RGB)
        _, buffer = cv2.imencode('.png', cv2.cvtColor(image, cv2.COLOR_RGB2BGR))
        return base64.b64encode(buffer).decode('utf-8')
    
    def _convert_to_pdf(self, html_path: Path) -> Path:
        try:
            from weasyprint import HTML
            pdf_path = html_path.with_suffix('.pdf')
            HTML(filename=str(html_path)).write_pdf(str(pdf_path))
            return pdf_path
        except ImportError:
            logger.warning("WeasyPrint not installed, returning HTML instead")
            return html_path


def generate_report(
    model_output: ModelOutput,
    decision_result: DecisionResult,
    analysis_id: str,
    heatmaps: Optional[dict] = None,
    format: ReportFormat = ReportFormat.HTML,
) -> Path:
    """Convenience function to generate a report."""
    generator = ClinicalReportGenerator()
    return generator.generate(model_output, decision_result, analysis_id, heatmaps, format)
